/*CESAR ARNULFO FORERO TEJADA*/


1. TRAMITO PERIMSO PARA FIRMAR CONTRATOS. 
2. SE SOLICITAD LA RESIDENCIA TEMPORAL POR CONVENIO MERCOSUR.  (OBTENER CALIDAD MIGRATORIO RESIDENTE - PAGAR 49,9 SOLES CODIGO 07561 EN BANCO DE NACION). 
3. SE SOLICITA CARNET DE EXTRANJERIA. DENTRO DE 2 DIAS HABILIDES. 


* TRAMITO PERIMSO PARA FIRMAR CONTRATOS. 
* CALIDAD MIGRATORIA TEMPORAL (MI CONTRATO ES DE 6 MESES). CONVENIO DE MERCOSUR. 

PARA EL CAMBIO DE APF Y ESSALUD LO PODRIA REALIZAR YO. 

XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXX
